---

- name: Install nginx
  action: $ansible_pkg_mgr name=nginx state=installed
  notify:
    - restart nginx

- name: Remove default nginx vhost
  action: file path=/etc/nginx/conf.d/default.conf state=absent
  notify:
    - restart nginx
