---

 - name: Ensure mongo package isn't locked
   lineinfile: dest=/etc/yum.repos.d/mongodb.repo
               regexp="exclude=mongo-10gen-server"
               state=absent

 - name: Install mongodb-server from mongodb yum repo
   action: yum
           name=mongo-10gen-server
           state=installed
   notify:
     - restart mongod
