# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :rpm_builder do |config|
    config.vm.box_url = 'http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box'
    config.vm.network :private_network, ip: '192.168.33.210'
    config.vm.box = 'centos6'

    config.vm.synced_folder './rpmbuild', '/home/builder/rpmbuild', owner: 'builder', group: 'root'
  end

  config.vm.define :test_app do |config|
    config.vm.box_url = 'http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box'
    config.vm.network :private_network, ip: '192.168.33.211'
    config.vm.box = 'centos6'

    config.vm.synced_folder './rpmbuild', '/home/builder/rpmbuild'
  end
end
