---

- copy: src=../files/mongodb.repo
       dest=/etc/yum.repos.d/

- name: Toggle repository
  ini_file: dest=/etc/yum.repos.d/mongodb.repo
            section=mongodb
            option=enabled
            value=1
