# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :db do |db_config|
    db_config.vm.box_url = 'http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box'
    db_config.vm.network :private_network, ip: '192.168.33.200'
    db_config.vm.box = 'centos6'

    db_config.vm.provision :ansible do |prov|
      prov.inventory_file = 'development'
      prov.sudo = true
      prov.playbook = './site.yml'
    end
  end
end
