---

 - name: Install mongodb-client from mongodb yum repo
   action: yum
           name={{ mongodb_client_package }}
           state=installed

 - name: Upgrade to latest mongodb-client from mongodb yum repo
   action: yum
           name={{ mongodb_client_package }}
           state=latest
   tags:
     - upgrade_mongodb_client
