# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :db do |db_config|
    db_config.vm.box_url = 'http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box'
    db_config.vm.box = 'centos64'
    db_config.vm.network :private_network, ip: '192.168.33.200'
  end

  config.vm.define :web do |web_config|
    web_config.vm.box_url = 'http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box'
    web_config.vm.box = 'centos64'
    web_config.vm.network :private_network, ip: '192.168.33.201'
  end
end
