---

 - name: Install mongodb-server from mongodb yum repo
   action: yum
           name={{ mongodb_server_package }}
           state=installed
   notify:
     - restart mongod

 - name: Upgrade to latest mongodb-server from mongodb yum repo
   action: yum
           name={{ mongodb_server_package }}
           state=latest
   tags:
     - upgrade_mongodb_server
   notify:
     - restart mongod
